CREATE TABLE User (
  id BIGINT PRIMARY KEY,
  email VARCHAR(255) UNIQUE,
  nickname VARCHAR(255),
  password VARCHAR(255),
  imageUrl VARCHAR(255),
  social ENUM('KAKAO', 'EMAIL'),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Token (
  id BIGINT PRIMARY KEY,
  user_id BIGINT,
  refreshToken VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES User (id)
);

CREATE TABLE Post (
  id BIGINT PRIMARY KEY,
  user_id BIGINT,
  title VARCHAR(255),
  content TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES User (id)
);

CREATE TABLE Comment (
  id BIGINT PRIMARY KEY,
  board_id BIGINT,
  user_id BIGINT,
  parent_id BIGINT,
  content TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (board_id) REFERENCES Post (id),
  FOREIGN KEY (user_id) REFERENCES User (id)
);
