name: leets-blog dev CI 파이프라인

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      checks: write
      pull-requests: write

    steps:
      # 1. GitHub 레포지토리 Checkout
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. JDK 17 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. application.properties 생성
      - name: application.properties 설정
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.properties

      # 4. Gradle Wrapper 실행 권한 부여
      - name: Gradle Wrapper 권한 부여
        run: chmod +x gradlew

      # 4-1. Gradle 캐싱 설정
      - name: Gradle 캐싱
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      # 5. Gradle 빌드
      - name: Gradle 빌드
        run: ./gradlew clean build

      # 6. DockerHub 로그인
      - name: DockerHub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      # 7. Docker 이미지 Build & Push
      - name: Docker 이미지 Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/leets-server:latest
